src/Form/Models/Upload.php
<?php
/**
 * Created by PhpStorm.
 * User: Estaban
 * Date: 13-12-2017
 * Time: 14:39
 */

namespace App\Form\Models;


class Upload {

	/**
	 * @var string
	 */
	private $file;

    /**
     * @var string
     */
	private $name;

	/**
	 * @var \DateTime
	 */
	private $added;

	/**
	 * @var string
	 */
	private $type;

	/**
	 * @var string
	 */
	private $visibility;

	/**
	 * @var \DateTime
	 */
	private $expires_at;

	/**
	 * @return string
	 */
	public function getFile(): ?string {
		return $this->file;
	}

	/**
	 * @param string $file
	 */
	public function setFile( string $file ): void {
		$this->file = $file;
	}

	/**
	 * @return \DateTime
	 */
	public function getAdded(): \DateTime {
		return $this->added;
	}

	/**
	 * @param \DateTime $added
	 */
	public function setAdded( \DateTime $added ): void {
		$this->added = $added;
	}

	/**
	 * @return string
	 */
	public function getType(): ?string {
		return $this->type;
	}

	/**
	 * @param string $type
	 */
	public function setType( string $type ): void {
		$this->type = $type;
	}

	/**
	 * @return string
	 */
	public function getVisibility(): ?string {
		return $this->visibility;
	}

	/**
	 * @param string $visibility
	 */
	public function setVisibility( string $visibility ): void {
		$this->visibility = $visibility;
	}

	/**
	 * @return \DateTime
	 */
	public function getExpiresAt(): \DateTime {
		return $this->expires_at;
	}

	/**
	 * @param \DateTime $expires_at
	 */
	public function setExpiresAt( \DateTime $expires_at ): void {
		$this->expires_at = $expires_at;
	}

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

}

src/Controller/ListController.php
<?php
/**
 * Created by PhpStorm.
 * User: Estaban
 * Date: 15-12-2017
 * Time: 14:51
 */

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class ListController extends Controller {

	/**
	 * @Route(path="/list/", name="list")
	 * @param Request $request
	 *
	 * @return Response
	 */
	public function ListAction(Request $request){
		$storage = $this->get('app.storage.aws');
		$user = $this->getDoctrine()->getRepository('App:User')->find(1);
		$page = $request->get('page');
		$limit = $request->get('limit');
		if(empty($page)){
			$page = 0;
		}
		if(empty($limit)){
			$limit = 10;
		}
		$items = $storage->listFromDatabase($user,$page,$limit);
		return $this->render('list/list.html.twig', array(
			'items' => $items['items'],
			'total' => $items['total'],
		));
	}

	/**
	 * @Route(path="/detail/{id}/", name="listDetail")
	 * @param $id
	 *
	 * @return Response
	 */
	public function detailAction($id){
		$storage = $this->get('app.storage.aws');
		$key = $storage->detailsFromDatabase($id);
		$item = $storage->fileDetails($key->getFileLink());
		return $this->render('list/detail.html.twig', array(
			'item' => $item,
			'key' => $key,
		));
	}

    /**
     * @Route(path="/delete/{key}/")
     * @param $key
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
	public function deleteAction($key){
        $storage = $this->get('app.storage.aws');
        $storage->deleteFile($key);
        return $this->redirectToRoute('list');
    }
}

templates/list/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('list') }}">List</a><br/>
{% if item is defined and item is not empty %}
{% if key.fileType == 'image/jpeg' or key.fileType == 'image/png' %}
    <img src="{{ item.url }}" alt="{{ key.fileName }}", width="150" height="150">
{% endif %}
    <p>Details:
        Name: {{ key.fileName }}<br/>
        Last modified {{ item.lastModified }}</p>
    <p>Link: <a href="{{ item.url }}" target="_blank">{{ item.url }}</a></p>
{% endif %}
{% endblock %}

templates/list/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <p><a href="{{ path('upload') }}">Upload</a> </p>
    {% if items is defined and items is not empty %}
        {% for item in items %}
            <p><a href="{{ path('listDetail',{id:item.id}) }}">{{ item.fileName }}</a> - expires at {{ item.expiresAt|date('Y-m-d') }}</p>
        {% endfor %}
    {% endif %}
{% endblock %}